server:
  port: 20002
  tomcat:
    accept-count: 10000
    max-connections: 1000
    max-threads: 500

spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    cache-refresh-executor-thread-pool-size: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    

feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
logging:
  file: service-out.log
  level:
    com.demo: DEBUG
    org.springframework: WARN
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
          
    